=head1 date.pl - Perl timezone converter script

Convert NZ-time strings to UK-time and vice-versa.

=head1 SYNOPSIS

    # Convert NZ datetime to GMT
    $ date.pl Tue Feb 03 07:00 NZDT 2015
    $ date.pl Tue Feb 03 07:00 GMT+1300 2015
    GMT: 2015-02-02T18:00:00
    
    # Convert GMT datetime to NZT
    $ date.pl 2015-01-17 13:24:00 GMT
    GMT: 2015-01-17T00:24:00
    
=head1 INSTALLATION

Simply copy the B<date.pl> script to a directory in your $PATH.
 
=head1 DEPENDENCIES

This module requires these other modules and libraries:

=over

=item * L<DateTime::Format::DateParse>

=item * L<Date::Parse>

=back


=cut

=head1 LICENCE

Copyright 2015 Dave Webb

date.pl is free software. You can do B<anything> you like with it.

=head1 CHANGES

=over

=item * 2015-03-26 - VERSION 0.93

Removed old attempt at extra timezone parsing. It didn't work well.

Added support for "N (minutes|hours|days) ago".

Converted functions to methods, so they can access the object's particular
local and remote timezones.

=item * 2015-03-26 - VERSION 0.92

Convert to modulino in prep for testing.

=item * 2015-03-26 - VERSION 0.91

Handle dates of the form "26 March 2015 at 06:55" as gmail presents in replies.

Handle unix timestamps.

Attempt to parse TZ from strings before calling DataParse.

=item * 2015-02-09 - VERSION 0.9

First release. Basic but working.


=cut

